// id не должен совпадать с реальными из базы
export default [
  {
    id: '1x',
    name: 'Круг',
    image: '/main_catlog/krug90plywood.jpg',
    icon: '/main_catlog/krug90plywood.jpg',
    size: '90',
    price: 46,
    material: 'plywood',
    typeCode: '0001',
  },
  {
    id: '2x',
    name: 'Квадрат',
    image: '/main_catlog/kvadrat90mdf.jpg',
    icon: '/main_catlog/kvadrat90mdf.jpg',
    size: '90',
    price: 53,
    material: 'mdf',
    typeCode: '0002',
  },
  {
    id: '3x',
    name: 'Круг',
    image: '/main_catlog/krug180plexiglas.jpg',
    icon: '/main_catlog/krug180plexiglas.jpg',
    size: '180',
    material: 'plexiglas',
    price: 492,
    typeCode: '0023',
  },
  {
    id: '4x',
    name: 'Круг',
    image: '/main_catlog/krug150acrilyc.jpg',
    icon: '/main_catlog/krug150acrilyc.jpg',
    size: '150',
    price: 545,
    material: 'acrylic_gold',
    typeCode: '0019',
  },
];
