export default [
  {
    id: '1',
    name: 'Круг',
    image: '/product/krug9.jpg',
    size: 9,
    count: 16,
    typeCode: '0001',
    material: 'plywood',
  },
  {
    id: '2',
    name: 'Круг',
    image: '/product/krug15.jpg',
    size: 15,
    count: 5,
    typeCode: '0001',
    material: 'plywood',
  },
  {
    id: '3',
    name: 'Круг',
    image: '/product/krug18.jpg',
    size: 18,
    count: 4,
    typeCode: '0001',
    material: 'plywood',
  },
  {
    id: '3',
    name: 'Круг',
    image: '/product/krug20.jpg',
    size: 20,
    count: 3,
    typeCode: '0001',
    material: 'plywood',
  },
  {
    id: '4',
    name: 'Круг',
    image: '/product/krug25.jpg',
    size: 25,
    count: 8,
    typeCode: '0001',
    material: 'plywood',
  },
  {
    id: '5',
    name: 'Круг',
    image: '/product/krug35.jpg',
    size: 35,
    count: 8,
    typeCode: '0001',
    material: 'plywood',
  },
];
